# Generated by Django 4.2.16 on 2025-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_avatar_url_message_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='', null=True),
        ),
    ]
