# Generated by Django 4.2.16 on 2025-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created'], name='base_messag_room_id_cd245e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created'], name='base_messag_created_c02514_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['updated'], name='base_room_updated_d87aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created'], name='base_room_created_b90438_idx'),
        ),
    ]
